// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Accessories() {
  return window['go']['main']['App']['Accessories']();
}

export function AccessoryKinds() {
  return window['go']['main']['App']['AccessoryKinds']();
}

export function AccessoryModel(arg1) {
  return window['go']['main']['App']['AccessoryModel'](arg1);
}

export function AccessoryTemplates() {
  return window['go']['main']['App']['AccessoryTemplates']();
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function BakeFigurine(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BakeFigurine'](arg1, arg2, arg3, arg4);
}

export function BrowseGameFolder() {
  return window['go']['main']['App']['BrowseGameFolder']();
}

export function CancelForgeInstall() {
  return window['go']['main']['App']['CancelForgeInstall']();
}

export function CancelImport() {
  return window['go']['main']['App']['CancelImport']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckModLoaded() {
  return window['go']['main']['App']['CheckModLoaded']();
}

export function ChooseGlobalCardBack() {
  return window['go']['main']['App']['ChooseGlobalCardBack']();
}

export function ChooseSetCardBack(arg1) {
  return window['go']['main']['App']['ChooseSetCardBack'](arg1);
}

export function Confirm(arg1) {
  return window['go']['main']['App']['Confirm'](arg1);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function DefaultArtColor(arg1) {
  return window['go']['main']['App']['DefaultArtColor'](arg1);
}

export function DefaultImportOptions() {
  return window['go']['main']['App']['DefaultImportOptions']();
}

export function DeleteAccessory(arg1) {
  return window['go']['main']['App']['DeleteAccessory'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function ForgeStatus() {
  return window['go']['main']['App']['ForgeStatus']();
}

export function GameStatus() {
  return window['go']['main']['App']['GameStatus']();
}

export function GamifyAccessoryApply(arg1) {
  return window['go']['main']['App']['GamifyAccessoryApply'](arg1);
}

export function GamifyAccessoryDefaults() {
  return window['go']['main']['App']['GamifyAccessoryDefaults']();
}

export function GamifyAccessoryPreview(arg1) {
  return window['go']['main']['App']['GamifyAccessoryPreview'](arg1);
}

export function GamifyApply(arg1, arg2, arg3) {
  return window['go']['main']['App']['GamifyApply'](arg1, arg2, arg3);
}

export function GamifyDefaults() {
  return window['go']['main']['App']['GamifyDefaults']();
}

export function GamifyPreview(arg1, arg2) {
  return window['go']['main']['App']['GamifyPreview'](arg1, arg2);
}

export function GenerateGlobalCardBack(arg1, arg2) {
  return window['go']['main']['App']['GenerateGlobalCardBack'](arg1, arg2);
}

export function GeneratePackArt(arg1, arg2, arg3) {
  return window['go']['main']['App']['GeneratePackArt'](arg1, arg2, arg3);
}

export function GenerateSetCardBack(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateSetCardBack'](arg1, arg2, arg3);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GlobalCardBack() {
  return window['go']['main']['App']['GlobalCardBack']();
}

export function ImportFigurineModel() {
  return window['go']['main']['App']['ImportFigurineModel']();
}

export function ImportScryfallSet(arg1, arg2) {
  return window['go']['main']['App']['ImportScryfallSet'](arg1, arg2);
}

export function InstallAccessories() {
  return window['go']['main']['App']['InstallAccessories']();
}

export function InstallForge() {
  return window['go']['main']['App']['InstallForge']();
}

export function InstallProject(arg1) {
  return window['go']['main']['App']['InstallProject'](arg1);
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function LaunchGame() {
  return window['go']['main']['App']['LaunchGame']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function LoadProject(arg1) {
  return window['go']['main']['App']['LoadProject'](arg1);
}

export function LocateGame() {
  return window['go']['main']['App']['LocateGame']();
}

export function ModSettings() {
  return window['go']['main']['App']['ModSettings']();
}

export function MoveAccessory(arg1, arg2) {
  return window['go']['main']['App']['MoveAccessory'](arg1, arg2);
}

export function NewAccessory(arg1, arg2, arg3) {
  return window['go']['main']['App']['NewAccessory'](arg1, arg2, arg3);
}

export function OpenAccessoriesFolder() {
  return window['go']['main']['App']['OpenAccessoriesFolder']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenProjectFolder(arg1) {
  return window['go']['main']['App']['OpenProjectFolder'](arg1);
}

export function PackIconFromTexture(arg1) {
  return window['go']['main']['App']['PackIconFromTexture'](arg1);
}

export function PickAccessoryImage() {
  return window['go']['main']['App']['PickAccessoryImage']();
}

export function PickImage(arg1, arg2) {
  return window['go']['main']['App']['PickImage'](arg1, arg2);
}

export function PickImages(arg1) {
  return window['go']['main']['App']['PickImages'](arg1);
}

export function ProjectInstallState(arg1) {
  return window['go']['main']['App']['ProjectInstallState'](arg1);
}

export function RefreshPrices(arg1) {
  return window['go']['main']['App']['RefreshPrices'](arg1);
}

export function RemoveForge() {
  return window['go']['main']['App']['RemoveForge']();
}

export function RemoveGlobalCardBack() {
  return window['go']['main']['App']['RemoveGlobalCardBack']();
}

export function RestoreModDefaults(arg1) {
  return window['go']['main']['App']['RestoreModDefaults'](arg1);
}

export function SaveAccessory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveAccessory'](arg1, arg2, arg3, arg4);
}

export function SaveAccessorySourceImage(arg1, arg2) {
  return window['go']['main']['App']['SaveAccessorySourceImage'](arg1, arg2);
}

export function SavePackArt(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SavePackArt'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}

export function SaveProjectImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveProjectImage'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScryfallSets(arg1) {
  return window['go']['main']['App']['ScryfallSets'](arg1);
}

export function SetModSetting(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetModSetting'](arg1, arg2, arg3);
}

export function SetupRepair() {
  return window['go']['main']['App']['SetupRepair']();
}

export function SetupState() {
  return window['go']['main']['App']['SetupState']();
}

export function SetupUninstall(arg1) {
  return window['go']['main']['App']['SetupUninstall'](arg1);
}

export function SnapshotPackBase(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SnapshotPackBase'](arg1, arg2, arg3, arg4);
}

export function SyncInstalledSets() {
  return window['go']['main']['App']['SyncInstalledSets']();
}

export function UninstallProject(arg1) {
  return window['go']['main']['App']['UninstallProject'](arg1);
}

export function ValidateProject(arg1) {
  return window['go']['main']['App']['ValidateProject'](arg1);
}
