// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {setfmt} from '../models';
import {uvmap} from '../models';
import {catalog} from '../models';
import {figurine} from '../models';
import {decoart} from '../models';
import {game} from '../models';
import {updater} from '../models';
import {project} from '../models';
import {debuglog} from '../models';
import {importer} from '../models';
import {art} from '../models';
import {library} from '../models';
import {forge} from '../models';
import {gamify} from '../models';
import {modconfig} from '../models';
import {installer} from '../models';

export function Accessories():Promise<main.AccessoryView>;

export function AccessoryKinds():Promise<Array<setfmt.AccessoryKind>>;

export function AccessoryModel(arg1:string):Promise<uvmap.Model>;

export function AccessoryTemplates():Promise<string>;

export function AddFromCatalog(arg1:string,arg2:Array<string>):Promise<catalog.AddResult>;

export function AppVersion():Promise<main.VersionInfo>;

export function BakeDecorationModel(arg1:string,arg2:string,arg3:string,arg4:figurine.Placement):Promise<main.DecorationBake>;

export function BakeFigurine(arg1:string,arg2:string,arg3:string,arg4:figurine.Placement):Promise<main.FigurineBake>;

export function BakeFurnitureModel(arg1:string,arg2:string,arg3:string,arg4:figurine.Placement):Promise<main.FurnitureBake>;

export function BakePoster(arg1:string,arg2:decoart.Poster):Promise<main.DecorationBake>;

export function BoxFromPack(arg1:string,arg2:string):Promise<main.BoxArt>;

export function BrowseGameFolder():Promise<game.Status>;

export function CancelForgeInstall():Promise<void>;

export function CancelImport():Promise<void>;

export function CancelStorage():Promise<void>;

export function CatalogAll(arg1:string):Promise<Array<catalog.Entry>>;

export function CatalogList(arg1:string):Promise<Array<catalog.Entry>>;

export function CheckForUpdate():Promise<updater.Release>;

export function CheckModLoaded():Promise<main.ModCheck>;

export function ChooseGlobalCardBack():Promise<string>;

export function ChooseSetCardBack(arg1:string):Promise<string>;

export function Confirm(arg1:string):Promise<boolean>;

export function CreateProject(arg1:string,arg2:string):Promise<project.Project>;

export function CreateSetup(arg1:string,arg2:string,arg3:boolean):Promise<main.SetupsView>;

export function DebugReport():Promise<debuglog.Report>;

export function DecorationKinds():Promise<Array<setfmt.DecorationKind>>;

export function DecorationTemplates():Promise<string>;

export function DefaultArtColor(arg1:string):Promise<string>;

export function DefaultImportOptions(arg1:string):Promise<importer.Options>;

export function DeleteAccessories(arg1:Array<string>):Promise<main.AccessoryView>;

export function DeleteAccessory(arg1:string):Promise<main.AccessoryView>;

export function DeleteDecoration(arg1:string):Promise<main.AccessoryView>;

export function DeleteDecorationMany(arg1:Array<string>):Promise<main.AccessoryView>;

export function DeleteFromCatalog(arg1:string,arg2:Array<string>):Promise<catalog.Deleted>;

export function DeleteFurniture(arg1:string):Promise<main.AccessoryView>;

export function DeleteFurnitureMany(arg1:Array<string>):Promise<main.AccessoryView>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteSetup(arg1:string):Promise<main.SetupsView>;

export function DeleteUnused(arg1:string,arg2:Array<string>):Promise<number>;

export function DetectBoxFaces(arg1:string,arg2:string):Promise<art.DisplayFaces>;

export function DifferPreview(arg1:string,arg2:string):Promise<library.DifferPreview>;

export function EPLModPath(arg1:string):Promise<string>;

export function ExportSetup(arg1:string):Promise<string>;

export function ForgeStatus():Promise<forge.Status>;

export function FurniturePaintTemplate(arg1:string):Promise<main.FurniturePaintInfo>;

export function FurniturePaintTemplateOwn(arg1:string,arg2:string,arg3:figurine.Placement):Promise<main.FurniturePaintInfo>;

export function FurnitureTemplates():Promise<string>;

export function FurnitureTypes():Promise<Array<setfmt.FurnitureType>>;

export function GameStatus():Promise<game.Status>;

export function GamifyAccessoryApply(arg1:gamify.AccessorySettings):Promise<Array<gamify.AccessoryPreview>>;

export function GamifyAccessoryDefaults():Promise<gamify.AccessorySettings>;

export function GamifyAccessoryPreview(arg1:gamify.AccessorySettings):Promise<Array<gamify.AccessoryPreview>>;

export function GamifyApply(arg1:Array<string>,arg2:gamify.Settings,arg3:boolean):Promise<Array<gamify.Preview>>;

export function GamifyDefaults():Promise<gamify.Settings>;

export function GamifyPreview(arg1:Array<string>,arg2:gamify.Settings):Promise<Array<gamify.Preview>>;

export function GenerateGlobalCardBack(arg1:string,arg2:string):Promise<string>;

export function GeneratePackArt(arg1:string,arg2:string,arg3:art.Options):Promise<art.Result>;

export function GenerateSetCardBack(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function GlobalCardBack():Promise<string>;

export function ImportEPL(arg1:string,arg2:main.EPLSelection):Promise<main.EPLResult>;

export function ImportFigurineModel():Promise<main.FigurineSource>;

export function ImportModelWithTextures(arg1:string,arg2:main.ModelTextures):Promise<main.FigurineSource>;

export function ImportSet(arg1:string,arg2:string,arg3:importer.Options):Promise<string>;

export function ImportSetup(arg1:string):Promise<string>;

export function ImportSources():Promise<Array<importer.SourceInfo>>;

export function InstallAccessories():Promise<main.AccessoryView>;

export function InstallForge():Promise<string>;

export function InstallProject(arg1:string):Promise<main.SaveResult>;

export function InstallUpdate():Promise<void>;

export function LaunchGame():Promise<void>;

export function LibraryArt(arg1:string,arg2:string,arg3:string):Promise<main.LibraryArtInfo>;

export function ListProjects():Promise<Array<project.Summary>>;

export function ListSetups():Promise<main.SetupsView>;

export function LoadProject(arg1:string):Promise<project.Project>;

export function LocateGame():Promise<game.Status>;

export function ModSettings():Promise<main.ModSettingsView>;

export function MoveAccessory(arg1:string,arg2:number):Promise<main.AccessoryView>;

export function MoveEverything():Promise<main.StorageResult>;

export function MoveSetup(arg1:string,arg2:number):Promise<main.SetupsView>;

export function NewAccessory(arg1:string,arg2:string,arg3:string):Promise<setfmt.Accessory>;

export function NewDecoration(arg1:string,arg2:string):Promise<setfmt.Decoration>;

export function NewFurniture(arg1:string,arg2:string,arg3:string):Promise<setfmt.Furniture>;

export function OpenAccessoriesFolder():Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenProjectFolder(arg1:string):Promise<void>;

export function OpenSetupFolder(arg1:string):Promise<void>;

export function PaintFurniture(arg1:string,arg2:string):Promise<setfmt.FurniturePaint>;

export function PickAccessoryImage():Promise<string>;

export function PickEPLFolder():Promise<string>;

export function PickEPLMod():Promise<string>;

export function PickImage(arg1:string,arg2:string):Promise<string>;

export function PickImages(arg1:string):Promise<Array<string>>;

export function PickImportFolder():Promise<string>;

export function PickPackAndBox(arg1:Array<importer.SealedProduct>,arg2:number):Promise<main.PickedProducts>;

export function PickSetupFile():Promise<main.SetupFileInfo>;

export function PreviewEPL(arg1:string,arg2:boolean):Promise<importer.EPLPreview>;

export function PreviewImportFolder(arg1:string,arg2:importer.Options):Promise<importer.FolderPreview>;

export function ProductPhotoSets(arg1:string,arg2:number):Promise<main.ProductPhotoSets>;

export function ProductPhotos(arg1:number,arg2:number):Promise<Array<importer.SealedProduct>>;

export function ProjectInstallState(arg1:string):Promise<string>;

export function RefreshPrices(arg1:string):Promise<string>;

export function RefreshTemplates(arg1:boolean):Promise<main.TemplatesStatus>;

export function RemoveForge():Promise<void>;

export function RemoveFromCatalog(arg1:string,arg2:Array<string>):Promise<void>;

export function RemoveGlobalCardBack():Promise<void>;

export function ResolveDiffering(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.StorageResult>;

export function RestoreModDefaults(arg1:string):Promise<number>;

export function RetrySetups():Promise<main.SetupsView>;

export function RotateCardImages(arg1:string,arg2:Array<string>,arg3:number,arg4:boolean):Promise<number>;

export function SaveAccessory(arg1:setfmt.Accessory,arg2:string,arg3:string,arg4:string):Promise<main.AccessoryView>;

export function SaveAccessorySourceImage(arg1:string,arg2:string):Promise<string>;

export function SaveAutoArt(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SaveDebugReport():Promise<string>;

export function SaveDecoration(arg1:setfmt.Decoration,arg2:string,arg3:string):Promise<main.AccessoryView>;

export function SaveFurniture(arg1:setfmt.Furniture,arg2:string,arg3:string):Promise<main.AccessoryView>;

export function SavePackArt(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.PackArtFiles>;

export function SaveProject(arg1:project.Project):Promise<main.SaveResult>;

export function SaveProjectImage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<main.Settings>;

export function SaveTemplateImage(arg1:string,arg2:string):Promise<string>;

export function SaveToCatalog(arg1:string,arg2:Array<string>):Promise<void>;

export function SetAccessoryIcons(arg1:Record<string, string>):Promise<void>;

export function SetModSetting(arg1:string,arg2:string,arg3:string):Promise<modconfig.Entry>;

export function SetupRepair():Promise<string>;

export function SetupState():Promise<installer.State>;

export function SetupUninstall(arg1:boolean):Promise<string>;

export function ShrinkPreview(arg1:string,arg2:string):Promise<library.ShrinkPreview>;

export function ShrinkSets(arg1:Record<string, Array<string>>):Promise<main.StorageResult>;

export function SmartArtSources(arg1:string,arg2:string,arg3:main.SmartChoice):Promise<main.SmartArtSources>;

export function SnapshotPackBase(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SourceSets(arg1:string,arg2:string,arg3:boolean):Promise<Array<main.ImportableSet>>;

export function StorageReport():Promise<library.Report>;

export function StorageTask():Promise<main.StorageTaskInfo>;

export function SwitchSetup(arg1:string):Promise<main.SwitchResult>;

export function SyncInstalledSets():Promise<string>;

export function TemplatesStatus():Promise<main.TemplatesStatus>;

export function UninstallProject(arg1:string):Promise<void>;

export function UpdateSetup(arg1:string,arg2:string,arg3:string):Promise<main.SetupsView>;

export function UseProductPhoto(arg1:string,arg2:importer.SealedProduct):Promise<string>;

export function UseSourceRarities(arg1:project.Project):Promise<project.Project>;

export function ValidateProject(arg1:string):Promise<Array<setfmt.Issue>>;

export function WaitReady():Promise<boolean>;
