// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Accessories() {
  return window['go']['main']['App']['Accessories']();
}

export function AccessoryKinds() {
  return window['go']['main']['App']['AccessoryKinds']();
}

export function AccessoryModel(arg1) {
  return window['go']['main']['App']['AccessoryModel'](arg1);
}

export function AccessoryTemplates() {
  return window['go']['main']['App']['AccessoryTemplates']();
}

export function AddFromCatalog(arg1, arg2) {
  return window['go']['main']['App']['AddFromCatalog'](arg1, arg2);
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function BakeDecorationModel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BakeDecorationModel'](arg1, arg2, arg3, arg4);
}

export function BakeFigurine(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BakeFigurine'](arg1, arg2, arg3, arg4);
}

export function BakeFurnitureModel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BakeFurnitureModel'](arg1, arg2, arg3, arg4);
}

export function BakePoster(arg1, arg2) {
  return window['go']['main']['App']['BakePoster'](arg1, arg2);
}

export function BoxFromPack(arg1, arg2) {
  return window['go']['main']['App']['BoxFromPack'](arg1, arg2);
}

export function BrowseGameFolder() {
  return window['go']['main']['App']['BrowseGameFolder']();
}

export function CancelForgeInstall() {
  return window['go']['main']['App']['CancelForgeInstall']();
}

export function CancelImport() {
  return window['go']['main']['App']['CancelImport']();
}

export function CancelStorage() {
  return window['go']['main']['App']['CancelStorage']();
}

export function CatalogAll(arg1) {
  return window['go']['main']['App']['CatalogAll'](arg1);
}

export function CatalogList(arg1) {
  return window['go']['main']['App']['CatalogList'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckModLoaded() {
  return window['go']['main']['App']['CheckModLoaded']();
}

export function ChooseGlobalCardBack() {
  return window['go']['main']['App']['ChooseGlobalCardBack']();
}

export function ChooseSetCardBack(arg1) {
  return window['go']['main']['App']['ChooseSetCardBack'](arg1);
}

export function ChooseShopSign() {
  return window['go']['main']['App']['ChooseShopSign']();
}

export function Confirm(arg1) {
  return window['go']['main']['App']['Confirm'](arg1);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function CreateSetup(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSetup'](arg1, arg2, arg3);
}

export function DebugReport() {
  return window['go']['main']['App']['DebugReport']();
}

export function DecorationKinds() {
  return window['go']['main']['App']['DecorationKinds']();
}

export function DecorationTemplates() {
  return window['go']['main']['App']['DecorationTemplates']();
}

export function DefaultArtColor(arg1) {
  return window['go']['main']['App']['DefaultArtColor'](arg1);
}

export function DefaultImportOptions(arg1) {
  return window['go']['main']['App']['DefaultImportOptions'](arg1);
}

export function DeleteAccessories(arg1) {
  return window['go']['main']['App']['DeleteAccessories'](arg1);
}

export function DeleteAccessory(arg1) {
  return window['go']['main']['App']['DeleteAccessory'](arg1);
}

export function DeleteDecoration(arg1) {
  return window['go']['main']['App']['DeleteDecoration'](arg1);
}

export function DeleteDecorationMany(arg1) {
  return window['go']['main']['App']['DeleteDecorationMany'](arg1);
}

export function DeleteFromCatalog(arg1, arg2) {
  return window['go']['main']['App']['DeleteFromCatalog'](arg1, arg2);
}

export function DeleteFurniture(arg1) {
  return window['go']['main']['App']['DeleteFurniture'](arg1);
}

export function DeleteFurnitureMany(arg1) {
  return window['go']['main']['App']['DeleteFurnitureMany'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteSetup(arg1) {
  return window['go']['main']['App']['DeleteSetup'](arg1);
}

export function DeleteUnused(arg1, arg2) {
  return window['go']['main']['App']['DeleteUnused'](arg1, arg2);
}

export function DetectBoxFaces(arg1, arg2) {
  return window['go']['main']['App']['DetectBoxFaces'](arg1, arg2);
}

export function DifferPreview(arg1, arg2) {
  return window['go']['main']['App']['DifferPreview'](arg1, arg2);
}

export function EPLModPath(arg1) {
  return window['go']['main']['App']['EPLModPath'](arg1);
}

export function ExportSetup(arg1) {
  return window['go']['main']['App']['ExportSetup'](arg1);
}

export function ForgeStatus() {
  return window['go']['main']['App']['ForgeStatus']();
}

export function FurniturePaintTemplate(arg1) {
  return window['go']['main']['App']['FurniturePaintTemplate'](arg1);
}

export function FurniturePaintTemplateOwn(arg1, arg2, arg3) {
  return window['go']['main']['App']['FurniturePaintTemplateOwn'](arg1, arg2, arg3);
}

export function FurnitureTemplates() {
  return window['go']['main']['App']['FurnitureTemplates']();
}

export function FurnitureTypes() {
  return window['go']['main']['App']['FurnitureTypes']();
}

export function GameStatus() {
  return window['go']['main']['App']['GameStatus']();
}

export function GamifyAccessoryApply(arg1) {
  return window['go']['main']['App']['GamifyAccessoryApply'](arg1);
}

export function GamifyAccessoryDefaults() {
  return window['go']['main']['App']['GamifyAccessoryDefaults']();
}

export function GamifyAccessoryPreview(arg1) {
  return window['go']['main']['App']['GamifyAccessoryPreview'](arg1);
}

export function GamifyApply(arg1, arg2, arg3) {
  return window['go']['main']['App']['GamifyApply'](arg1, arg2, arg3);
}

export function GamifyDefaults() {
  return window['go']['main']['App']['GamifyDefaults']();
}

export function GamifyPreview(arg1, arg2) {
  return window['go']['main']['App']['GamifyPreview'](arg1, arg2);
}

export function GenerateGlobalCardBack(arg1, arg2) {
  return window['go']['main']['App']['GenerateGlobalCardBack'](arg1, arg2);
}

export function GeneratePackArt(arg1, arg2, arg3) {
  return window['go']['main']['App']['GeneratePackArt'](arg1, arg2, arg3);
}

export function GenerateSetCardBack(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateSetCardBack'](arg1, arg2, arg3);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GlobalCardBack() {
  return window['go']['main']['App']['GlobalCardBack']();
}

export function ImportEPL(arg1, arg2) {
  return window['go']['main']['App']['ImportEPL'](arg1, arg2);
}

export function ImportFigurineModel() {
  return window['go']['main']['App']['ImportFigurineModel']();
}

export function ImportModelWithTextures(arg1, arg2) {
  return window['go']['main']['App']['ImportModelWithTextures'](arg1, arg2);
}

export function ImportSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportSet'](arg1, arg2, arg3);
}

export function ImportSetup(arg1) {
  return window['go']['main']['App']['ImportSetup'](arg1);
}

export function ImportSources() {
  return window['go']['main']['App']['ImportSources']();
}

export function InstallAccessories() {
  return window['go']['main']['App']['InstallAccessories']();
}

export function InstallForge() {
  return window['go']['main']['App']['InstallForge']();
}

export function InstallProject(arg1) {
  return window['go']['main']['App']['InstallProject'](arg1);
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function LaunchGame() {
  return window['go']['main']['App']['LaunchGame']();
}

export function LibraryArt(arg1, arg2, arg3) {
  return window['go']['main']['App']['LibraryArt'](arg1, arg2, arg3);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListSetups() {
  return window['go']['main']['App']['ListSetups']();
}

export function LoadProject(arg1) {
  return window['go']['main']['App']['LoadProject'](arg1);
}

export function LocateGame() {
  return window['go']['main']['App']['LocateGame']();
}

export function ModSettings() {
  return window['go']['main']['App']['ModSettings']();
}

export function MoveAccessory(arg1, arg2) {
  return window['go']['main']['App']['MoveAccessory'](arg1, arg2);
}

export function MoveEverything() {
  return window['go']['main']['App']['MoveEverything']();
}

export function MoveSetup(arg1, arg2) {
  return window['go']['main']['App']['MoveSetup'](arg1, arg2);
}

export function NewAccessory(arg1, arg2, arg3) {
  return window['go']['main']['App']['NewAccessory'](arg1, arg2, arg3);
}

export function NewDecoration(arg1, arg2) {
  return window['go']['main']['App']['NewDecoration'](arg1, arg2);
}

export function NewFurniture(arg1, arg2, arg3) {
  return window['go']['main']['App']['NewFurniture'](arg1, arg2, arg3);
}

export function OpenAccessoriesFolder() {
  return window['go']['main']['App']['OpenAccessoriesFolder']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenProjectFolder(arg1) {
  return window['go']['main']['App']['OpenProjectFolder'](arg1);
}

export function OpenSetupFolder(arg1) {
  return window['go']['main']['App']['OpenSetupFolder'](arg1);
}

export function PackPresets() {
  return window['go']['main']['App']['PackPresets']();
}

export function PaintFurniture(arg1, arg2) {
  return window['go']['main']['App']['PaintFurniture'](arg1, arg2);
}

export function PickAccessoryImage() {
  return window['go']['main']['App']['PickAccessoryImage']();
}

export function PickEPLFolder() {
  return window['go']['main']['App']['PickEPLFolder']();
}

export function PickEPLMod() {
  return window['go']['main']['App']['PickEPLMod']();
}

export function PickImage(arg1, arg2) {
  return window['go']['main']['App']['PickImage'](arg1, arg2);
}

export function PickImages(arg1) {
  return window['go']['main']['App']['PickImages'](arg1);
}

export function PickImportFolder() {
  return window['go']['main']['App']['PickImportFolder']();
}

export function PickPackAndBox(arg1, arg2) {
  return window['go']['main']['App']['PickPackAndBox'](arg1, arg2);
}

export function PickSetupFile() {
  return window['go']['main']['App']['PickSetupFile']();
}

export function PreviewEPL(arg1, arg2) {
  return window['go']['main']['App']['PreviewEPL'](arg1, arg2);
}

export function PreviewImportFolder(arg1, arg2) {
  return window['go']['main']['App']['PreviewImportFolder'](arg1, arg2);
}

export function ProductPhotoSets(arg1, arg2) {
  return window['go']['main']['App']['ProductPhotoSets'](arg1, arg2);
}

export function ProductPhotos(arg1, arg2) {
  return window['go']['main']['App']['ProductPhotos'](arg1, arg2);
}

export function ProjectInstallState(arg1) {
  return window['go']['main']['App']['ProjectInstallState'](arg1);
}

export function RefreshPrices(arg1) {
  return window['go']['main']['App']['RefreshPrices'](arg1);
}

export function RefreshTemplates(arg1) {
  return window['go']['main']['App']['RefreshTemplates'](arg1);
}

export function RemoveForge() {
  return window['go']['main']['App']['RemoveForge']();
}

export function RemoveFromCatalog(arg1, arg2) {
  return window['go']['main']['App']['RemoveFromCatalog'](arg1, arg2);
}

export function RemoveGlobalCardBack() {
  return window['go']['main']['App']['RemoveGlobalCardBack']();
}

export function RemoveShopSign() {
  return window['go']['main']['App']['RemoveShopSign']();
}

export function ResolveDiffering(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResolveDiffering'](arg1, arg2, arg3, arg4);
}

export function RestoreModDefaults(arg1) {
  return window['go']['main']['App']['RestoreModDefaults'](arg1);
}

export function RetrySetups() {
  return window['go']['main']['App']['RetrySetups']();
}

export function RotateCardImages(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RotateCardImages'](arg1, arg2, arg3, arg4);
}

export function SaveAccessory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveAccessory'](arg1, arg2, arg3, arg4);
}

export function SaveAccessorySourceImage(arg1, arg2) {
  return window['go']['main']['App']['SaveAccessorySourceImage'](arg1, arg2);
}

export function SaveAutoArt(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveAutoArt'](arg1, arg2, arg3, arg4);
}

export function SaveDebugReport() {
  return window['go']['main']['App']['SaveDebugReport']();
}

export function SaveDecoration(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveDecoration'](arg1, arg2, arg3);
}

export function SaveFurniture(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFurniture'](arg1, arg2, arg3);
}

export function SavePackArt(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SavePackArt'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}

export function SaveProjectImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveProjectImage'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveTemplateImage(arg1, arg2) {
  return window['go']['main']['App']['SaveTemplateImage'](arg1, arg2);
}

export function SaveToCatalog(arg1, arg2) {
  return window['go']['main']['App']['SaveToCatalog'](arg1, arg2);
}

export function SetAccessoryIcons(arg1) {
  return window['go']['main']['App']['SetAccessoryIcons'](arg1);
}

export function SetModSetting(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetModSetting'](arg1, arg2, arg3);
}

export function SetShopSignCrop(arg1) {
  return window['go']['main']['App']['SetShopSignCrop'](arg1);
}

export function SetShopSignFont(arg1, arg2) {
  return window['go']['main']['App']['SetShopSignFont'](arg1, arg2);
}

export function SetShopSignShowName(arg1) {
  return window['go']['main']['App']['SetShopSignShowName'](arg1);
}

export function SetShopSignText(arg1) {
  return window['go']['main']['App']['SetShopSignText'](arg1);
}

export function SetupRepair() {
  return window['go']['main']['App']['SetupRepair']();
}

export function SetupState() {
  return window['go']['main']['App']['SetupState']();
}

export function SetupUninstall(arg1) {
  return window['go']['main']['App']['SetupUninstall'](arg1);
}

export function ShopSign() {
  return window['go']['main']['App']['ShopSign']();
}

export function ShopSignFonts() {
  return window['go']['main']['App']['ShopSignFonts']();
}

export function ShrinkPreview(arg1, arg2) {
  return window['go']['main']['App']['ShrinkPreview'](arg1, arg2);
}

export function ShrinkSets(arg1) {
  return window['go']['main']['App']['ShrinkSets'](arg1);
}

export function SmartArtSources(arg1, arg2, arg3) {
  return window['go']['main']['App']['SmartArtSources'](arg1, arg2, arg3);
}

export function SnapshotPackBase(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SnapshotPackBase'](arg1, arg2, arg3, arg4);
}

export function SourceSets(arg1, arg2, arg3) {
  return window['go']['main']['App']['SourceSets'](arg1, arg2, arg3);
}

export function StorageReport() {
  return window['go']['main']['App']['StorageReport']();
}

export function StorageTask() {
  return window['go']['main']['App']['StorageTask']();
}

export function SwitchSetup(arg1) {
  return window['go']['main']['App']['SwitchSetup'](arg1);
}

export function SyncInstalledSets() {
  return window['go']['main']['App']['SyncInstalledSets']();
}

export function TemplatesStatus() {
  return window['go']['main']['App']['TemplatesStatus']();
}

export function UninstallProject(arg1) {
  return window['go']['main']['App']['UninstallProject'](arg1);
}

export function UpdateSetup(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSetup'](arg1, arg2, arg3);
}

export function UseProductPhoto(arg1, arg2) {
  return window['go']['main']['App']['UseProductPhoto'](arg1, arg2);
}

export function UseSourceRarities(arg1) {
  return window['go']['main']['App']['UseSourceRarities'](arg1);
}

export function ValidateProject(arg1) {
  return window['go']['main']['App']['ValidateProject'](arg1);
}

export function WaitReady() {
  return window['go']['main']['App']['WaitReady']();
}
