// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {setfmt} from '../models';
import {uvmap} from '../models';
import {figurine} from '../models';
import {game} from '../models';
import {updater} from '../models';
import {project} from '../models';
import {importer} from '../models';
import {forge} from '../models';
import {gamify} from '../models';
import {art} from '../models';
import {modconfig} from '../models';
import {installer} from '../models';

export function Accessories():Promise<main.AccessoryView>;

export function AccessoryKinds():Promise<Array<setfmt.AccessoryKind>>;

export function AccessoryModel(arg1:string):Promise<uvmap.Model>;

export function AccessoryTemplates():Promise<string>;

export function AppVersion():Promise<main.VersionInfo>;

export function BakeFigurine(arg1:string,arg2:string,arg3:string,arg4:figurine.Placement):Promise<main.FigurineBake>;

export function BakeFurnitureModel(arg1:string,arg2:string,arg3:string,arg4:figurine.Placement):Promise<main.FurnitureBake>;

export function BrowseGameFolder():Promise<game.Status>;

export function CancelForgeInstall():Promise<void>;

export function CancelImport():Promise<void>;

export function CheckForUpdate():Promise<updater.Release>;

export function CheckModLoaded():Promise<main.ModCheck>;

export function ChooseGlobalCardBack():Promise<string>;

export function ChooseSetCardBack(arg1:string):Promise<string>;

export function Confirm(arg1:string):Promise<boolean>;

export function CreateProject(arg1:string,arg2:string):Promise<project.Project>;

export function CreateSetup(arg1:string,arg2:string,arg3:boolean):Promise<main.SetupsView>;

export function DefaultArtColor(arg1:string):Promise<string>;

export function DefaultImportOptions(arg1:string):Promise<importer.Options>;

export function DeleteAccessory(arg1:string):Promise<main.AccessoryView>;

export function DeleteFurniture(arg1:string):Promise<main.AccessoryView>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteSetup(arg1:string):Promise<main.SetupsView>;

export function ExportSetup(arg1:string):Promise<string>;

export function ForgeStatus():Promise<forge.Status>;

export function FurnitureTemplates():Promise<string>;

export function FurnitureTypes():Promise<Array<setfmt.FurnitureType>>;

export function GameStatus():Promise<game.Status>;

export function GamifyAccessoryApply(arg1:gamify.AccessorySettings):Promise<Array<gamify.AccessoryPreview>>;

export function GamifyAccessoryDefaults():Promise<gamify.AccessorySettings>;

export function GamifyAccessoryPreview(arg1:gamify.AccessorySettings):Promise<Array<gamify.AccessoryPreview>>;

export function GamifyApply(arg1:Array<string>,arg2:gamify.Settings,arg3:boolean):Promise<Array<gamify.Preview>>;

export function GamifyDefaults():Promise<gamify.Settings>;

export function GamifyPreview(arg1:Array<string>,arg2:gamify.Settings):Promise<Array<gamify.Preview>>;

export function GenerateGlobalCardBack(arg1:string,arg2:string):Promise<string>;

export function GeneratePackArt(arg1:string,arg2:string,arg3:art.Options):Promise<art.Result>;

export function GenerateSetCardBack(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function GlobalCardBack():Promise<string>;

export function ImportFigurineModel():Promise<main.FigurineSource>;

export function ImportSet(arg1:string,arg2:string,arg3:importer.Options):Promise<string>;

export function ImportSetup(arg1:string):Promise<string>;

export function ImportSources():Promise<Array<importer.SourceInfo>>;

export function InstallAccessories():Promise<main.AccessoryView>;

export function InstallForge():Promise<string>;

export function InstallProject(arg1:string):Promise<main.SaveResult>;

export function InstallUpdate():Promise<void>;

export function LaunchGame():Promise<void>;

export function ListProjects():Promise<Array<project.Summary>>;

export function ListSetups():Promise<main.SetupsView>;

export function LoadProject(arg1:string):Promise<project.Project>;

export function LocateGame():Promise<game.Status>;

export function ModSettings():Promise<main.ModSettingsView>;

export function MoveAccessory(arg1:string,arg2:number):Promise<main.AccessoryView>;

export function MoveSetup(arg1:string,arg2:number):Promise<main.SetupsView>;

export function NewAccessory(arg1:string,arg2:string,arg3:string):Promise<setfmt.Accessory>;

export function NewFurniture(arg1:string,arg2:string,arg3:string):Promise<setfmt.Furniture>;

export function OpenAccessoriesFolder():Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenProjectFolder(arg1:string):Promise<void>;

export function OpenSetupFolder(arg1:string):Promise<void>;

export function PackIconFromTexture(arg1:string):Promise<string>;

export function PickAccessoryImage():Promise<string>;

export function PickImage(arg1:string,arg2:string):Promise<string>;

export function PickImages(arg1:string):Promise<Array<string>>;

export function PickSetupFile():Promise<main.SetupFileInfo>;

export function ProjectInstallState(arg1:string):Promise<string>;

export function RefreshPrices(arg1:string):Promise<string>;

export function RefreshTemplates(arg1:boolean):Promise<main.TemplatesStatus>;

export function RemoveForge():Promise<void>;

export function RemoveGlobalCardBack():Promise<void>;

export function RestoreModDefaults(arg1:string):Promise<number>;

export function RetrySetups():Promise<main.SetupsView>;

export function SaveAccessory(arg1:setfmt.Accessory,arg2:string,arg3:string,arg4:string):Promise<main.AccessoryView>;

export function SaveAccessorySourceImage(arg1:string,arg2:string):Promise<string>;

export function SaveFurniture(arg1:setfmt.Furniture,arg2:string,arg3:string):Promise<main.AccessoryView>;

export function SavePackArt(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.PackArtFiles>;

export function SaveProject(arg1:project.Project):Promise<main.SaveResult>;

export function SaveProjectImage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<main.Settings>;

export function SetModSetting(arg1:string,arg2:string,arg3:string):Promise<modconfig.Entry>;

export function SetupRepair():Promise<string>;

export function SetupState():Promise<installer.State>;

export function SetupUninstall(arg1:boolean):Promise<string>;

export function SnapshotPackBase(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SourceSets(arg1:string,arg2:string,arg3:boolean):Promise<Array<main.ImportableSet>>;

export function SwitchSetup(arg1:string):Promise<main.SwitchResult>;

export function SyncInstalledSets():Promise<string>;

export function TemplatesStatus():Promise<main.TemplatesStatus>;

export function UninstallProject(arg1:string):Promise<void>;

export function UpdateSetup(arg1:string,arg2:string,arg3:string):Promise<main.SetupsView>;

export function ValidateProject(arg1:string):Promise<Array<setfmt.Issue>>;

export function WaitReady():Promise<boolean>;
